# Generated by Django 3.1.6 on 2021-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial_squashed_0007_bookmarks_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
