# Generated by Django 3.1.6 on 2021-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210221_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
