# Generated by Django 3.1.6 on 2021-02-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210221_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='create_date',
        ),
    ]
