# Generated by Django 3.1.6 on 2021-02-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
